version: '3.8'

services:
  backend:
    build:
      context: ../backend
    ports:
      - "8000:8000"  # Порт для Flask
    environment:
      FLASK_APP: main.py
    command: ["flask", "run", "--host=0.0.0.0", "--port=8000"]
    networks:
      - backend-network
    volumes:
      - container-data:/app

  frontend:
    build:
      context: ../frontend
    ports:
      - "8002:8002"
    environment:
      XDG_RUNTIME_DIR: /tmp/runtime-dir
    depends_on:
      - backend
    # Сеть, к которой будет подключен сервис
    networks:
      backend-network:
        # Алиасы для сети
        aliases:
          - localhost
    # Дополнительные хосты для сети
    extra_hosts:
      - "localhost:host-gateway"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    # Зависимости от других сервисов
    depends_on:
      - backend
      - frontend
    networks:
      - backend-network

volumes:
  container-data: null
networks:
  backend-network:
    driver: bridge

